/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AashiQ
 */
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    Random random=new Random();
    String s="jButton1";
    int i=0,p=0,total=0;
    ImageIcon g= new ImageIcon(Board.class.getResource("/image/g.png"));
    ImageIcon g_g= new ImageIcon(Board.class.getResource("/image/g_g.png"));
    ImageIcon one= new ImageIcon(Board.class.getResource("/image/1.png"));
    ImageIcon four= new ImageIcon(Board.class.getResource("/image/4.jpg"));
    ImageIcon eight= new ImageIcon(Board.class.getResource("/image/8.jpg"));
    ImageIcon twelve= new ImageIcon(Board.class.getResource("/image/12.jpg"));
    ImageIcon seventen= new ImageIcon(Board.class.getResource("/image/17.jpg"));
        ImageIcon thirtyfour= new ImageIcon(Board.class.getResource("/image/34.jpg"));
    ImageIcon fourtyone= new ImageIcon(Board.class.getResource("/image/41.jpg"));
    ImageIcon twentytwo= new ImageIcon(Board.class.getResource("/image/22.jpg"));
    ImageIcon twentyeight= new ImageIcon(Board.class.getResource("/image/28.jpg"));
    ImageIcon fourtyeight= new ImageIcon(Board.class.getResource("/image/48.jpg"));
    public Board() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dice.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 540, 80, 70);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ladder.png"))); // NOI18N
        jPanel1.add(jLabel61);
        jLabel61.setBounds(450, 170, 90, 170);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/snake_1.png"))); // NOI18N
        jPanel1.add(jLabel58);
        jLabel58.setBounds(260, 30, 100, 130);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ladder.png"))); // NOI18N
        jPanel1.add(jLabel60);
        jLabel60.setBounds(170, 20, 80, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 290, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(209, 235, 50, 50);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/snake_1.png"))); // NOI18N
        jLabel59.setText("jLabel59");
        jLabel59.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel59HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel59);
        jLabel59.setBounds(90, 180, 100, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(209, 179, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(209, 123, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(265, 123, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(321, 123, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(377, 123, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/8.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(437, 123, 50, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(437, 179, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(437, 235, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(437, 291, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/12.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(437, 347, 50, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(381, 347, 50, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(325, 347, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(269, 347, 50, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(209, 347, 50, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/17.jpg"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(153, 347, 50, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(153, 291, 50, 50);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(153, 235, 50, 50);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(153, 179, 50, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(153, 123, 50, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/22.jpg"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(153, 67, 50, 50);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(209, 67, 50, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel24);
        jLabel24.setBounds(265, 67, 50, 50);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(321, 67, 50, 50);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(377, 67, 50, 50);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel27);
        jLabel27.setBounds(437, 67, 50, 50);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/28.jpg"))); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(493, 67, 50, 50);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(493, 123, 50, 50);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(493, 179, 50, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(493, 235, 50, 50);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(493, 291, 50, 50);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel33);
        jLabel33.setBounds(493, 347, 50, 50);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/34.jpg"))); // NOI18N
        jPanel1.add(jLabel34);
        jLabel34.setBounds(493, 403, 50, 50);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel35);
        jLabel35.setBounds(437, 403, 50, 50);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel36);
        jLabel36.setBounds(381, 403, 50, 50);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel37);
        jLabel37.setBounds(325, 403, 50, 50);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel38);
        jLabel38.setBounds(269, 403, 50, 50);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel39);
        jLabel39.setBounds(209, 403, 50, 50);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel40);
        jLabel40.setBounds(153, 403, 50, 50);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/41.jpg"))); // NOI18N
        jPanel1.add(jLabel41);
        jLabel41.setBounds(97, 403, 50, 50);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel42);
        jLabel42.setBounds(97, 347, 50, 50);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel43);
        jLabel43.setBounds(97, 291, 50, 50);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel44);
        jLabel44.setBounds(97, 235, 50, 50);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel45);
        jLabel45.setBounds(97, 179, 50, 50);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel46);
        jLabel46.setBounds(97, 123, 50, 50);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel47);
        jLabel47.setBounds(97, 67, 50, 50);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/48.jpg"))); // NOI18N
        jPanel1.add(jLabel48);
        jLabel48.setBounds(97, 11, 50, 50);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel49);
        jLabel49.setBounds(153, 11, 50, 50);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel50);
        jLabel50.setBounds(209, 11, 50, 50);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel51);
        jLabel51.setBounds(265, 11, 50, 50);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel52);
        jLabel52.setBounds(321, 11, 50, 50);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel53);
        jLabel53.setBounds(377, 11, 50, 50);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel54);
        jLabel54.setBounds(437, 11, 50, 50);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g.png"))); // NOI18N
        jPanel1.add(jLabel55);
        jLabel55.setBounds(493, 11, 50, 50);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/55.jpg"))); // NOI18N
        jPanel1.add(jLabel56);
        jLabel56.setBounds(550, 10, 50, 50);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/start.png"))); // NOI18N
        jPanel1.add(jLabel57);
        jLabel57.setBounds(270, 180, 160, 160);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 540, 70, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(510, 540, 80, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           int dice=1+random.nextInt(6);
           if(p==0)
           {
               if(dice==1)
               {
                  // JOptionPane.showMessageDialog(null,"This time you through for ONE","So you enter the play", JOptionPane.PLAIN_MESSAGE);
                   JOptionPane.showMessageDialog(null, "This time you through for ONE \nSo you enter the play", "Output of Dice", JOptionPane.INFORMATION_MESSAGE);
                   p++;
               }
               else
               {
                   String f=Integer.toString(dice);
                   JOptionPane.showMessageDialog(null,"This time you through for "+f+"\nSo try again", "Output of Dice", JOptionPane.ERROR_MESSAGE);
                   i++;
               }
           }
           if(i==10)
           {
               
               JOptionPane.showMessageDialog(null,"Please Press refresh button and  try again","Output of Dice", JOptionPane.PLAIN_MESSAGE);
               jButton2.setVisible(true);
               jButton1.setVisible(false);
           }
           if(p==1)
           {
               String f=Integer.toString(dice);
                   JOptionPane.showMessageDialog(null,"This time you through for "+f,"Output of Dice", JOptionPane.PLAIN_MESSAGE);
               if(total==1)
                   jLabel1.setIcon(one);
               else
               if(total==2)
                   jLabel2.setIcon(g);
               else
               if(total==3)
                   jLabel3.setIcon(g);
               else
               if(total==4)
                   jLabel4.setIcon(four);
               else
               if(total==5)
                   jLabel5.setIcon(g);
               else
               if(total==6)
                   jLabel6.setIcon(g);
               else
               if(total==7)
                   jLabel7.setIcon(g);
               else
               if(total==8)
                   jLabel8.setIcon(eight);
               else
               if(total==9)
                   jLabel9.setIcon(g);
               else
               if(total==10)
                   jLabel10.setIcon(g);
               else
               if(total==11)
                   jLabel11.setIcon(g);
               else
               if(total==12)
                   jLabel12.setIcon(twelve);
               else
               if(total==13)
                   jLabel13.setIcon(g);
               else
               if(total==14)
                   jLabel14.setIcon(g);
               else
               if(total==15)
                   jLabel15.setIcon(g);
               else
               if(total==16)
                   jLabel16.setIcon(g);
               else
               if(total==17)
                   jLabel17.setIcon(seventen);
               else
               if(total==18)
                   jLabel18.setIcon(g);
               else
               if(total==19)
                   jLabel19.setIcon(g);
               else
               if(total==20)
                   jLabel20.setIcon(g);
               else
               if(total==21)
                   jLabel21.setIcon(g);
               else
               if(total==22)
                   jLabel22.setIcon(twentytwo);
               else
               if(total==23)
                   jLabel23.setIcon(g);
               else
               if(total==24)
                   jLabel24.setIcon(g);
               else
               if(total==25)
                   jLabel25.setIcon(g);
               else
               if(total==26)
                   jLabel26.setIcon(g);
               else
               if(total==27)
                   jLabel27.setIcon(g);
               else
               if(total==28)
                   jLabel28.setIcon(twentyeight);
               else
               if(total==29)
                   jLabel29.setIcon(g);
               else
               if(total==30)
                   jLabel30.setIcon(g);
               else
               if(total==31)
                   jLabel31.setIcon(g);
               else
               if(total==32)
                   jLabel32.setIcon(g);
               else
               if(total==33)
                   jLabel33.setIcon(g);
               else
               if(total==34)
                   jLabel34.setIcon(thirtyfour);
               else
               if(total==35)
                   jLabel35.setIcon(g);
               else
               if(total==36)
                   jLabel36.setIcon(g);
               else
               if(total==37)
                   jLabel37.setIcon(g);
               else
               if(total==38)
                   jLabel38.setIcon(g);
               else
               if(total==39)
                   jLabel39.setIcon(g);
               else
               if(total==40)
                   jLabel40.setIcon(g);
               else
               if(total==41)
                   jLabel41.setIcon(fourtyone);
               else
               if(total==42)
                   jLabel42.setIcon(g);
               else
               if(total==43)
                   jLabel43.setIcon(g);
               else
               if(total==44)
                   jLabel44.setIcon(g);
               else
               if(total==45)
                   jLabel45.setIcon(g);
               else
               if(total==46)
                   jLabel46.setIcon(g);
               else
               if(total==47)
                   jLabel47.setIcon(g);
               else
               if(total==48)
                   jLabel48.setIcon(fourtyeight);
               else
               if(total==49)
                   jLabel49.setIcon(g);
               else
               if(total==50)
                   jLabel50.setIcon(g);
               else
               if(total==51)
                   jLabel51.setIcon(g);
               else
               if(total==52)
                   jLabel52.setIcon(g);
               else
               if(total==53)
                   jLabel53.setIcon(g);
               else
               if(total==54)
                   jLabel54.setIcon(g);
               else
               if(total==55)
                   jLabel55.setIcon(g);
               else
               if(total==56)
                   jLabel56.setIcon(g);

               total+=dice;
               if(total==1)
                   jLabel1.setIcon(g_g);
               else
               if(total==2)
                   jLabel2.setIcon(g_g);
               else
               if(total==3)
                   jLabel3.setIcon(g_g);
               else
               if(total==4)
                   jLabel4.setIcon(g_g);
               else
               if(total==5)
                   jLabel5.setIcon(g_g);
               else
               if(total==6)
                   jLabel6.setIcon(g_g);
               else
               if(total==7)
                   jLabel7.setIcon(g_g);
               else
               if(total==8)
                   jLabel8.setIcon(g_g);
               else
               if(total==9)
                   jLabel9.setIcon(g_g);
               else
               if(total==10)
                   jLabel10.setIcon(g_g);
               else
               if(total==11)
                   jLabel11.setIcon(g_g);
               else
               if(total==12)
                   jLabel12.setIcon(g_g);
               else
               if(total==13)
                   jLabel13.setIcon(g_g);
               else
               if(total==14)
                   jLabel14.setIcon(g_g);
               else
               if(total==15)
                   jLabel15.setIcon(g_g);
               else
               if(total==16)
                   jLabel16.setIcon(g_g);
               else
               if(total==17)
                   jLabel17.setIcon(g_g);
               else
               if(total==18)
                   jLabel18.setIcon(g_g);
               else
               if(total==19)
                   jLabel19.setIcon(g_g);
               else
               if(total==20)
                   jLabel20.setIcon(g_g);
               else
               if(total==21)
                   jLabel21.setIcon(g_g);
               else
               if(total==22)
                   jLabel22.setIcon(g_g);
               else
               if(total==23)
                   jLabel23.setIcon(g_g);
               else
               if(total==24)
                   jLabel24.setIcon(g_g);
               else
               if(total==25)
                   jLabel25.setIcon(g_g);
               else
               if(total==26)
                   jLabel26.setIcon(g_g);
               else
               if(total==27)
                   jLabel27.setIcon(g_g);
               else
               if(total==28)
                   jLabel28.setIcon(g_g);
               else
               if(total==29)
                   jLabel29.setIcon(g_g);
               else
               if(total==30)
                   jLabel30.setIcon(g_g);
               else
               if(total==31)
                   jLabel31.setIcon(g_g);
               else
               if(total==32)
                   jLabel32.setIcon(g_g);
               else
               if(total==33)
                   jLabel33.setIcon(g_g);
               else
               if(total==34)
                   jLabel34.setIcon(g_g);
               else
               if(total==35)
                   jLabel35.setIcon(g_g);
               else
               if(total==36)
                   jLabel36.setIcon(g_g);
               else
               if(total==37)
                   jLabel37.setIcon(g_g);
               else
               if(total==38)
                   jLabel38.setIcon(g_g);
               else
               if(total==39)
                   jLabel39.setIcon(g_g);
               else
               if(total==40)
                   jLabel40.setIcon(g_g);
               else
               if(total==41)
                   jLabel41.setIcon(g_g);
               else
               if(total==42)
                   jLabel42.setIcon(g_g);
               else
               if(total==43)
                   jLabel43.setIcon(g_g);
               else
               if(total==44)
                   jLabel44.setIcon(g_g);
               else
               if(total==45)
                   jLabel45.setIcon(g_g);
               else
               if(total==46)
                   jLabel46.setIcon(g_g);
               else
               if(total==47)
                   jLabel47.setIcon(g_g);
               else
               if(total==48)
                   jLabel48.setIcon(g_g);
               else
               if(total==49)
                   jLabel49.setIcon(g_g);
               else
               if(total==50)
                   jLabel50.setIcon(g_g);
               else
               if(total==51)
                   jLabel51.setIcon(g_g);
               else
               if(total==52)
                   jLabel52.setIcon(g_g);
               else
               if(total==53)
                   jLabel53.setIcon(g_g);
               else
               if(total==54)
                   jLabel54.setIcon(g_g);
               else
               if(total==55)
                   jLabel55.setIcon(g_g);
               else
               if(total>=56)
               {
                   jLabel56.setIcon(g_g);
                   JOptionPane.showMessageDialog(null,"You finished the game","Game Over", JOptionPane.INFORMATION_MESSAGE);
               jButton2.setVisible(true);
               jButton1.setVisible(false);
               }
               
               
               if(total==11)
               {
                   total=30;
                   jLabel11.setIcon(g);
                   jLabel30.setIcon(g_g);
               }
               if(total==21)
               {
                   total=50;
                   jLabel21.setIcon(g);
                   jLabel50.setIcon(g_g);
               }
               if(total==45)
               {
                   total=19;
                   jLabel45.setIcon(g);
                   jLabel19.setIcon(g_g);
               }
               if(total==51)
               {
                   total=6;
                   jLabel51.setIcon(g);
                   jLabel6.setIcon(g_g);
               }
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Reset().reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
        jButton2.setVisible(false);
    }//GEN-LAST:event_jLabel1PropertyChange

    private void jLabel59HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel59HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59HierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
